// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3WS4jiWppuqwjRJnkVUGDmGpU-PS_gfg',
    appId: '1:644450403462:web:9a739f490358cc0f677d07',
    messagingSenderId: '644450403462',
    projectId: 'chasajo-12e3a',
    authDomain: 'chasajo-12e3a.firebaseapp.com',
    storageBucket: 'chasajo-12e3a.appspot.com',
    measurementId: 'G-CG71PDPL2H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDM7BS1auRNdSK_MlsGI1RxIWGDQlHGRFA',
    appId: '1:644450403462:android:7b8ec58ba5b689c0677d07',
    messagingSenderId: '644450403462',
    projectId: 'chasajo-12e3a',
    storageBucket: 'chasajo-12e3a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTrNQviu1JX9nfDGthYAIBz6CIKixErkY',
    appId: '1:644450403462:ios:913feedb8f87b060677d07',
    messagingSenderId: '644450403462',
    projectId: 'chasajo-12e3a',
    storageBucket: 'chasajo-12e3a.appspot.com',
    iosClientId: '644450403462-8kv0ismu1bdk3rqpk5ife252p3v7g66m.apps.googleusercontent.com',
    iosBundleId: 'com.example.chaSaJoFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTrNQviu1JX9nfDGthYAIBz6CIKixErkY',
    appId: '1:644450403462:ios:913feedb8f87b060677d07',
    messagingSenderId: '644450403462',
    projectId: 'chasajo-12e3a',
    storageBucket: 'chasajo-12e3a.appspot.com',
    iosClientId: '644450403462-8kv0ismu1bdk3rqpk5ife252p3v7g66m.apps.googleusercontent.com',
    iosBundleId: 'com.example.chaSaJoFlutter',
  );
}
